import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
mkdirSync('.sites-runtime',{recursive:true});
for(const [name,source] of [['model','src/model.ts'],['clipboard','src/clipboard.ts'],['worker','worker/index.ts'],['pdf','src/invoice-pdf.ts'],['component','src/app.component.ts'],['mobile-app','src/mobile-app.ts']]) await build({entryPoints:[source],outfile:`.sites-runtime/check-${name}.mjs`,bundle:true,format:'esm',platform:'node',target:'node24',packages:'external'});
const model=await import(pathToFileURL(process.cwd()+'/.sites-runtime/check-model.mjs'));
const clipboard=await import(pathToFileURL(process.cwd()+'/.sites-runtime/check-clipboard.mjs'));
const {default:worker}=await import(pathToFileURL(process.cwd()+'/.sites-runtime/check-worker.mjs'));
const {createInvoicePdf}=await import(pathToFileURL(process.cwd()+'/.sites-runtime/check-pdf.mjs'));
const doc=model.newInvoice();doc.billTo='Firefly Alpharetta';doc.invoiceNo='20260921-04';doc.invoiceDate='2026-09-21';
doc.rows=[['2026-08-05',50],['2026-08-19',25],['2026-08-21',50],['2026-08-26',50],['2026-08-28',50]].map(([date,meetha])=>({...model.newRow(date),meetha}));
assert.equal(model.totals(doc.rows).meetha,225);assert.equal(model.totals(doc.rows).grandTotal,450);assert.equal(model.invoiceError(doc),'');
const mixed={...doc,rows:[...doc.rows,{...model.newRow('2026-08-29'),flavour:17}]};assert.equal(model.totals(mixed.rows).grandTotal,501);assert.equal(model.totals(mixed.rows).flavour,17);
const custom={...mixed,meethaRate:2.75,flavourRate:3.50};assert.equal(model.totals(custom.rows,custom).grandTotal,678.25);assert.equal(model.rowAmount(custom.rows[0],custom),137.50);
assert.equal(model.totals([{...model.newRow('2026-10-02'),meetha:1,flavour:1}],{meethaRate:0.1,flavourRate:0.2}).grandTotal,0.3);
assert.equal(model.invoiceError({...doc,meethaRate:0,flavourRate:0}),'');
const {meethaRate,flavourRate,...legacy}=doc;assert.equal(model.cleanInvoice(legacy).meethaRate,2);assert.equal(model.cleanInvoice(legacy).flavourRate,3);
for(const rate of [-1,NaN,Infinity,null,'2.50',1.234,10000.01])assert.throws(()=>model.cleanInvoice({...doc,meethaRate:rate}));
assert.equal(model.newInvoice(2,custom).meethaRate,2.75);assert.equal(model.newInvoice().flavourRate,3);
const series=[{...model.newRow('2028-02-28'),meetha:10},model.newRow(),model.newRow()];const filled=model.filledRows(series,0,2);assert.deepEqual(filled.map(r=>r.date),['2028-02-28','2028-02-29','2028-03-01']);assert.equal(filled[0].meetha,10);assert.equal(series[1].date,'');
assert.equal(model.addDays('2026-12-31',1),'2027-01-01');assert.equal(model.addDays('2026-03-07',2),'2026-03-09');
assert.deepEqual(model.filledRows([model.newRow(),model.newRow(),model.newRow('2026-10-05')],2,0).map(r=>r.date),['2026-10-03','2026-10-04','2026-10-05']);
assert.deepEqual(model.filledRows([model.newRow('2026-10-01'),model.newRow(),model.newRow()],0,2,7).map(r=>r.date),['2026-10-01','2026-10-08','2026-10-15']);
assert.throws(()=>model.addDays('2026-02-30',1));assert.throws(()=>model.cleanInvoice({...doc,rows:[{...doc.rows[0],meetha:-1}]}));assert.throws(()=>model.cleanInvoice({...doc,rows:[{...doc.rows[0],flavour:1.5}]}));assert.throws(()=>model.cleanInvoice({...doc,rows:[doc.rows[0],doc.rows[0]]}));
assert.match(model.invoiceError({...doc,rows:[{...doc.rows[0],date:''}]}),/delivery date/);
console.log('PASS: exact prices and totals, leap/month/year/DST date filling, backward and weekly fills, invalid quantity/date rejection.');
const base=[{...model.newRow('2026-09-01'),meetha:7,flavour:8}];const original=structuredClone(base);
const excel='Delivery date\tMeetha\tFlavour\r\n"05-Aug-26"\t"1,000"\t2\r\n8/19/2026\t25.00\t\r\n';
const pasted=clipboard.pasteLedgerCells(base,0,'date',excel);assert.equal(pasted.cellCount,6);assert.equal(pasted.rows.length,2);
assert.deepEqual(pasted.rows.map(r=>[r.date,r.meetha,r.flavour]),[['2026-08-05',1000,2],['2026-08-19',25,0]]);assert.deepEqual(base,original);
const roundTrip=clipboard.pasteLedgerCells([model.newRow()],0,'date',clipboard.copyLedgerCells(pasted.rows));assert.deepEqual(roundTrip.rows.map(r=>[r.date,r.meetha,r.flavour]),pasted.rows.map(r=>[r.date,r.meetha,r.flavour]));
const headedExcel='Date\tMeeth Quantity\tFlavor Quantity\r\n01-Apr-26\t10\t\r\n03-Apr-26\t7\t\r\n06-Apr-26\t5\t8\r\n09-Apr-26\t12\t\r\n12-Apr-26\t6\t\r\n';
const headedPaste=clipboard.pasteLedgerCells(base,0,'date',headedExcel);
assert.deepEqual(headedPaste.rows.map(r=>[r.date,r.meetha,r.flavour]),[['2026-04-01',10,0],['2026-04-03',7,0],['2026-04-06',5,8],['2026-04-09',12,0],['2026-04-12',6,0]]);
assert.equal(headedPaste.rowCount,5);assert.equal(headedPaste.cellCount,15);assert.equal(model.totals(headedPaste.rows).grandTotal,104);assert.deepEqual(base,original);
for(const heading of ['Meetha Quantity','Meeta Quantity','Meeth Quantity','Meeeth Quantity'])assert.equal(clipboard.pasteLedgerCells(base,0,'date',headedExcel.replace('Meeth Quantity',heading)).rows[0].meetha,10);
const typoHeadingPaste=clipboard.pasteLedgerCells(base,0,'date',headedExcel.replace('Meeth Quantity','Meeeth Quantity'));
assert.deepEqual(typoHeadingPaste.rows.map(r=>[r.date,r.meetha,r.flavour]),headedPaste.rows.map(r=>[r.date,r.meetha,r.flavour]));assert.equal(model.totals(typoHeadingPaste.rows).grandTotal,104);assert.deepEqual(base,original);
assert.throws(()=>clipboard.pasteLedgerCells(base,0,'date',headedExcel.replace('Meeth Quantity','Unknown heading')),/Heading 2:.*Meetha/);assert.deepEqual(base,original);
const quantitiesWithHeaders=clipboard.pasteLedgerCells(base,0,'meetha','Meeth Quantity\tFlavor Quantity\n10\t19');assert.equal(quantitiesWithHeaders.rows[0].date,base[0].date);assert.equal(quantitiesWithHeaders.rows[0].flavour,19);
assert.throws(()=>clipboard.pasteLedgerCells(base,0,'date','Date\tMeeth Quantity\tFlavor Quantity'),/headings but no delivery cells/);
assert.throws(()=>clipboard.pasteLedgerCells(base,0,'date','Date\tFlavor Quantity\tMeeth Quantity\n02-Apr-26\t40\t19'),/Heading 2:.*Meetha/);assert.deepEqual(base,original);
const partial=clipboard.pasteLedgerCells(pasted.rows,1,'meetha','10\t3\n12\t4');assert.equal(partial.rows[1].date,'2026-08-19');assert.equal(partial.rows[2].date,'');assert.equal(partial.rows[2].flavour,4);
assert.equal(clipboard.pasteLedgerCells(base,0,'flavour','6').rows[0].meetha,7);
assert.equal(clipboard.excelDate('25569'),'1970-01-01');assert.equal(clipboard.excelDate('1'),'1900-01-01');assert.equal(clipboard.excelDate('59'),'1900-02-28');assert.equal(clipboard.excelDate('61'),'1900-03-01');assert.equal(clipboard.excelDate('2/29/28'),'2028-02-29');assert.equal(clipboard.excelDate('October 2, 2026'),'2026-10-02');
for(const value of ['60','2/29/2026','garbage'])assert.throws(()=>clipboard.excelDate(value));
assert.equal(clipboard.excelDate('14/04/2026'),'2026-04-14');
assert.equal(clipboard.excelDate('02/04/2026','dmy'),'2026-04-02');
assert.equal(clipboard.excelDate('02/04/2026','mdy'),'2026-02-04');
for(const value of ['2026/4/2','2026.04.02','02.Apr.26','Apr-02-26','Thursday, April 2, 2026','02\u00a0April\u00a02026','46114','46114.5','46,114.75','04/02/2026 12:30 PM','2026-04-02T00:00:00Z'])assert.equal(clipboard.excelDate(value),'2026-04-02');
const dayFirstExcel='Date\tMeeth Quantity\tFlavor Quantity\n02/04/2026\t10\t2\n14/04/2026\t5\t';
const dayFirstPaste=clipboard.pasteLedgerCells(base,0,'date',dayFirstExcel);
assert.deepEqual(dayFirstPaste.rows.map(r=>r.date),['2026-04-02','2026-04-14']);assert.equal(dayFirstPaste.dateOrder,'dmy');assert.equal(model.totals(dayFirstPaste.rows).grandTotal,36);assert.deepEqual(base,original);
const monthFirstPaste=clipboard.pasteLedgerCells(base,0,'date','4/2/2026\t10\t2\n4/14/2026\t5\t');
assert.deepEqual(monthFirstPaste.rows.map(r=>r.date),['2026-04-02','2026-04-14']);assert.equal(monthFirstPaste.dateOrder,'mdy');
assert.equal(clipboard.pasteLedgerCells(base,0,'date','02/04/2026\t1', 'dmy').rows[0].date,'2026-04-02');
assert.equal(clipboard.pasteLedgerCells(base,0,'date','02/04/2026\t1').rows[0].date,'2026-02-04');
for(const order of ['auto','mdy','dmy'])assert.deepEqual(clipboard.pasteLedgerCells(base,0,'date',clipboard.copyLedgerCells(dayFirstPaste.rows),order).rows.map(r=>r.date),['2026-04-02','2026-04-14']);
for(const value of ['31/02/2026','2026/02/30','60.5','0','2958466','46114.5oops','Aprilish 2, 2026','04/02/2026 25:00','2026-04-02T12:99:00Z'])assert.throws(()=>clipboard.excelDate(value));
assert.throws(()=>clipboard.pasteLedgerCells(base,0,'date','14/04/2026\t1\n04/14/2026\t2'),/mix day\/month and month\/day/);assert.deepEqual(base,original);
assert.throws(()=>clipboard.pasteLedgerCells(base,0,'date',dayFirstExcel,'mdy'));assert.deepEqual(base,original);
console.log('PASS: day/month and month/day inference/overrides, named and year-first dates, Excel date-time numbers, date-only times, stable copy round trips and atomic date errors.');
for(const value of ['-1','1.5','1000001','oops'])assert.throws(()=>clipboard.pasteLedgerCells(base,0,'meetha',value));
assert.throws(()=>clipboard.pasteLedgerCells(base,0,'date','10/02/2026\t10\t2\n10/03/2026\tinvalid\t4'));assert.deepEqual(base,original);
assert.throws(()=>clipboard.pasteLedgerCells(base,0,'flavour','2\t3'));assert.throws(()=>clipboard.pasteLedgerCells(base,0,'meetha','1\t2\n3'));
assert.equal(clipboard.pasteLedgerCells(base,0,'meetha',Array(500).fill('1').join('\n')).rows.length,500);assert.throws(()=>clipboard.pasteLedgerCells(base,0,'date',Array(501).fill('10/02/2026').join('\n')));
console.log('PASS: editable cent-accurate rates, legacy defaults, invalid rate rejection, Excel dates/quantities, copy/paste round trip, partial-column paste, appended rows and atomic failure/row limits.');
const sqlite=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
const DB={prepare(sql){const st=sqlite.prepare(sql);let values=[];return {bind(...v){values=v;return this;},async first(){return st.get(...values)??null;},async all(){return {results:st.all(...values)};},async run(){return {meta:{changes:st.run(...values).changes}};}};}};
const request=(path,method='GET',body,owner='owner-a',origin='https://paan.test')=>worker.fetch(new Request('https://paan.test'+path,{method,headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),origin,'Content-Type':'application/json'},...(body===undefined?{}:{body:typeof body==='string'?body:JSON.stringify(body)})}),{DB});
let res=await request('/api/invoices/'+doc.id,'PUT',{invoice:doc,revision:0});assert.equal(res.status,200);assert.equal((await res.json()).revision,1);
res=await request('/api/invoices/'+doc.id);assert.deepEqual((await res.json()).invoice,doc);
res=await request('/api/invoices');assert.equal((await res.json()).invoices.length,1);
res=await request('/api/invoices','GET',undefined,'owner-b');assert.equal((await res.json()).invoices.length,0);
assert.equal((await request('/api/invoices/'+doc.id,'GET',undefined,'owner-b')).status,404);
assert.equal((await request('/api/invoices','GET',undefined,'')).status,401);
assert.equal((await request('/api/invoices/'+doc.id,'PUT',{invoice:doc,revision:0},'owner-b')).status,409);
assert.equal((await request('/api/invoices/'+doc.id,'PUT',{invoice:custom,revision:1})).status,200);
assert.equal((await request('/api/invoices/'+doc.id,'PUT',{invoice:doc,revision:1})).status,409);
assert.equal((await request('/api/invoices/'+doc.id,'PUT','{bad json')).status,400);
assert.equal((await request('/api/invoices/'+doc.id,'PUT',{invoice:doc,revision:2},'owner-a','https://other.test')).status,403);
res=await request('/api/invoices/'+doc.id);assert.equal((await res.json()).invoice.rows.length,6);
res=await request('/api/invoices/'+doc.id);assert.deepEqual((await res.json()).invoice,custom);
assert.equal((await request('/api/invoices/'+doc.id,'PUT',{invoice:{...custom,flavourRate:-3},revision:2})).status,400);
const legacyId=crypto.randomUUID();sqlite.prepare('INSERT INTO invoices (id,owner_id,payload,revision,updated_at) VALUES (?,?,?,?,?)').run(legacyId,'owner-a',JSON.stringify({...legacy,id:legacyId}),1,new Date().toISOString());
res=await request('/api/invoices/'+legacyId);const old=(await res.json()).invoice;assert.equal(old.meethaRate,2);assert.equal(old.flavourRate,3);assert.equal(model.totals(old.rows,old).grandTotal,450);
console.log('PASS: real SQLite migration, save/read/list round trip, owner isolation, stale-write protection and rejected invalid/cross-origin writes.');
const logo='data:image/png;base64,'+readFileSync('public/paan-party-logo.png').toString('base64');
const fonts={regular:readFileSync('public/fonts/PaanSans.ttf').toString('base64'),bold:readFileSync('public/fonts/PaanSans-Bold.ttf').toString('base64'),italic:readFileSync('public/fonts/PaanSans-Oblique.ttf').toString('base64')};
const pdf=createInvoicePdf(custom,logo,fonts);assert.equal(pdf.getNumberOfPages(),1);writeFileSync('.sites-runtime/sample-invoice.pdf',Buffer.from(pdf.output('arraybuffer')));
const long={...custom,rows:Array.from({length:100},(_,i)=>({...model.newRow(model.addDays('2026-01-01',i)),meetha:50,flavour:3}))};const longPdf=createInvoicePdf(long,logo,fonts);assert(longPdf.getNumberOfPages()>1);writeFileSync('.sites-runtime/long-invoice.pdf',Buffer.from(longPdf.output('arraybuffer')));
console.log('PASS: branded PDF creation and multi-page pagination.');
await import('@angular/compiler');
const {AppComponent}=await import(pathToFileURL(process.cwd()+'/.sites-runtime/check-component.mjs'));
const pasteDialogApp=new AppComponent();let pasteDialogClosed=false;
pasteDialogApp.draft.set({...doc,rows:[model.newRow()]});pasteDialogApp.pasteDialog={nativeElement:{close(){pasteDialogClosed=true;}}};pasteDialogApp.setClipboardText(headedExcel.replace('Meeth Quantity','Meeeth Quantity'));
assert.equal(pasteDialogApp.clipboardPreview().rowCount,5);assert.match(pasteDialogApp.clipboardPreview().dates,/Apr 01, 2026/);
pasteDialogApp.pasteFromDialog();assert(pasteDialogClosed);assert.equal(pasteDialogApp.clipboardError(),'');assert.equal(pasteDialogApp.draft().rows.length,5);assert.equal(pasteDialogApp.summary().grandTotal,104);pasteDialogApp.ngOnDestroy();
console.log('PASS: Excel heading spellings, blank flavour cells, April dates/totals, partial-column headings, rejected reordered headings and paste dialog import.');
const datePasteApp=new AppComponent();let dateDialogClosed=false;
datePasteApp.draft.set({...doc,rows:[model.newRow()]});datePasteApp.pasteDialog={nativeElement:{close(){dateDialogClosed=true;}}};datePasteApp.setClipboardText(dayFirstExcel);
assert.equal(datePasteApp.clipboardPreview().dateOrder,'dmy');assert.match(datePasteApp.clipboardPreview().dates,/Apr 02, 2026/);assert.equal(datePasteApp.draft().rows[0].date,'');
datePasteApp.setClipboardText('02/04/2026\t10\t2');assert.match(datePasteApp.clipboardPreview().dates,/Feb 04, 2026/);
datePasteApp.clipboardError.set('old error');datePasteApp.setExcelDateOrder('dmy');assert.equal(datePasteApp.clipboardError(),'');assert.match(datePasteApp.clipboardPreview().dates,/Apr 02, 2026/);
datePasteApp.pasteFromDialog();assert(dateDialogClosed);assert.equal(datePasteApp.draft().rows[0].date,'2026-04-02');assert.equal(datePasteApp.summary().grandTotal,26);
let datePastePrevented=false;datePasteApp.pasteCells({preventDefault(){datePastePrevented=true;},clipboardData:{getData(){return '03/04/2026\t5\t1';}}},datePasteApp.draft().rows[0].id,'date');assert(datePastePrevented);assert.equal(datePasteApp.draft().rows[0].date,'2026-04-03');
const beforeInvalidDate=structuredClone(datePasteApp.draft());dateDialogClosed=false;datePasteApp.setClipboardText('31/02/2026\t1\t2');assert.equal(datePasteApp.clipboardPreview(),null);datePasteApp.pasteFromDialog();assert(!dateDialogClosed);assert.match(datePasteApp.clipboardError(),/valid calendar date/);assert.deepEqual(datePasteApp.draft(),beforeInvalidDate);
datePasteApp.setClipboardText('02-Apr-26\t1\t2');assert.equal(datePasteApp.clipboardError(),'');datePasteApp.focusCell(0,'meetha');assert.equal(datePasteApp.clipboardPreview(),null);datePasteApp.ngOnDestroy();
console.log('PASS: non-mutating date preview, numeric date-order changes, direct paste consistency and rejected date imports keeping the dialog and invoice intact.');
const {appHomeUrl,runningAsApp}=await import(pathToFileURL(process.cwd()+'/.sites-runtime/check-mobile-app.mjs'));
assert.equal(appHomeUrl('https://paan.example/api/invoices/customer-id?token=private#invoice'), 'https://paan.example/');
assert.equal(appHomeUrl('https://user:password@paan.example/login?code=secret'), 'https://paan.example/');
assert.equal(appHomeUrl('file:///local/private'), '');assert.equal(runningAsApp(),false);
const manifest=JSON.parse(readFileSync('public/manifest.webmanifest','utf8'));
assert.equal(manifest.display,'standalone');assert.equal(manifest.id,'/');assert.equal(manifest.start_url,'/');
for(const size of [192,512]){
  const icon=manifest.icons.find(icon=>icon.sizes===`${size}x${size}`);assert(icon);
  const png=readFileSync('public'+icon.src);assert.equal(png.readUInt32BE(16),size);assert.equal(png.readUInt32BE(20),size);
}
const appleIcon=readFileSync('public/icons/apple-touch-icon.png');assert.equal(appleIcon.readUInt32BE(16),180);assert.equal(appleIcon.readUInt32BE(20),180);
const installer=new AppComponent();let prompts=0;let deferred=false;
installer.prepareInstallation({preventDefault(){deferred=true;},async prompt(){prompts++;},userChoice:Promise.resolve({outcome:'accepted'})});
assert(deferred);assert.equal(prompts,0);assert(installer.installAvailable());
await installer.installApp();await installer.installApp();assert.equal(prompts,1);assert(!installer.installed());assert(!installer.installAvailable());
installer.installationComplete();assert(installer.installed());installer.ngOnDestroy();
const dismissedInstall=new AppComponent();dismissedInstall.prepareInstallation({preventDefault(){},async prompt(){},userChoice:Promise.resolve({outcome:'dismissed'})});
await dismissedInstall.installApp();assert(!dismissedInstall.installed());assert(!dismissedInstall.installing());assert.match(dismissedInstall.notice(),/later/);dismissedInstall.ngOnDestroy();
const failedInstall=new AppComponent();failedInstall.prepareInstallation({preventDefault(){},async prompt(){throw new Error('Unavailable');},userChoice:Promise.resolve({outcome:'dismissed'})});
await failedInstall.installApp();assert(!failedInstall.installing());assert(!failedInstall.installed());assert.match(failedInstall.notice(),/steps below/);failedInstall.ngOnDestroy();
const originalNavigator=Object.getOwnPropertyDescriptor(globalThis,'navigator');let shared;let copied='';
try{
  const sharingApp=new AppComponent();sharingApp.shareUrl.set(appHomeUrl('https://paan.example/invoice?login=secret'));
  Object.defineProperty(globalThis,'navigator',{configurable:true,value:{async share(data){shared=data;}}});
  await sharingApp.shareAppLink();assert.deepEqual(shared,{title:'Paan Party Invoice',text:'Open the Paan Party invoice app.',url:'https://paan.example/'});
  Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{async writeText(text){copied=text;}}}});
  await sharingApp.shareAppLink();assert.equal(copied,'https://paan.example/');
  copied='';Object.defineProperty(globalThis,'navigator',{configurable:true,value:{async share(){throw new DOMException('Cancelled','AbortError');},clipboard:{async writeText(text){copied=text;}}}});
  await sharingApp.shareAppLink();assert.equal(copied,'');assert(!sharingApp.sharing());sharingApp.ngOnDestroy();
}finally{if(originalNavigator)Object.defineProperty(globalThis,'navigator',originalNavigator);else delete globalThis.navigator;}
console.log('PASS: installable manifest/icon sizes, accepted/dismissed/failed installation handling, single-use browser prompts, clean app links, native sharing and clipboard fallback.');
const app=new AppComponent();app.draft.set({...doc,rows:series});app.request=async()=>({revision:app.revision+1,updatedAt:new Date().toISOString()});
app.startFill({preventDefault(){},stopPropagation(){}},0);app.drag.set({from:0,to:2});app.finishFill();assert.deepEqual(app.draft().rows.map(r=>r.date),['2028-02-28','2028-02-29','2028-03-01']);assert.equal(await app.saveNow(),true);assert.equal(app.state(),'saved');
app.fillCount=4;app.fillStep=7;app.fillDates();assert.equal(app.draft().rows.length,4);assert.equal(app.draft().rows[3].date,'2028-03-20');
app.moveRow(app.draft().rows[3].id,-1);assert.equal(app.draft().rows[2].date,'2028-03-20');
app.removeRow(app.draft().rows[0].id);assert.equal(app.draft().rows.length,3);
app.draft.set({...doc,rows:[model.newRow()]});let prevented=false;let savedInvoice;
app.request=async(path,options)=>{savedInvoice=JSON.parse(options.body).invoice;return {revision:app.revision+1,updatedAt:new Date().toISOString()};};
app.pasteCells({preventDefault(){prevented=true;},clipboardData:{getData(){return '10/02/2026\t10\t2\n10/03/2026\t5\t3';}}},app.draft().rows[0].id,'date');assert(prevented);assert.equal(app.draft().rows.length,2);
app.rateField('meethaRate',2.55);app.rateField('flavourRate',3.5);assert.equal(app.summary().grandTotal,55.75);assert.equal(app.amount(app.draft().rows[0]),32.5);assert.equal(await app.saveNow(),true);assert.equal(savedInvoice.meethaRate,2.55);assert.equal(savedInvoice.rows.length,2);
const reopened=new AppComponent();reopened.request=async()=>({invoice:savedInvoice,revision:3});await reopened.loadInvoice(savedInvoice.id);assert.equal(reopened.summary().grandTotal,55.75);
reopened.newDialog={nativeElement:{close(){}}};await reopened.confirmNew();assert.equal(reopened.draft().meethaRate,2.55);assert.equal(reopened.draft().flavourRate,3.5);assert.equal(savedInvoice.rows.length,2);reopened.ngOnDestroy();
app.ngOnDestroy();console.log('PASS: Angular component drag completion, touch/keyboard fill control, saving, reordering and deletion.');
console.log('PASS: direct paste event, rate recalculation, saved pasted quantities/rates, reopening and new-invoice rate reuse.');
const resetApp=new AppComponent();
const api=async(path,options={})=>{const response=await request(path,options.method??'GET',options.body?JSON.parse(options.body):undefined);const data=await response.json();if(!response.ok)throw new Error(data.error);return data;};
resetApp.request=api;resetApp.saved.set((await api('/api/invoices')).invoices);await resetApp.loadInvoice(doc.id);
let opened=false;let closed=false;resetApp.resetDialog={nativeElement:{showModal(){opened=true;},close(){closed=true;}}};
const beforeReset=structuredClone(resetApp.draft());resetApp.openReset();assert(opened);assert.deepEqual(resetApp.draft(),beforeReset);
let releaseSave;let signalStarted;let firstWrite=true;
const heldSave=new Promise(resolve=>{releaseSave=resolve;});const startedSave=new Promise(resolve=>{signalStarted=resolve;});
resetApp.request=async(path,options={})=>{if(firstWrite&&options.method==='PUT'){firstWrite=false;signalStarted();await heldSave;}return api(path,options);};
resetApp.field('billTo','Pending save');const pendingSave=resetApp.saveNow();await startedSave;
resetApp.focusCell(5,'flavour');resetApp.fillOpen.set(true);resetApp.setClipboardText('old clipboard');
const resetOperation=resetApp.confirmReset();assert(resetApp.resetting());releaseSave();await Promise.all([pendingSave,resetOperation]);
const cleared=(await api('/api/invoices/'+doc.id)).invoice;
assert.equal(cleared.id,doc.id);assert.equal(cleared.billTo,'');assert.equal(cleared.invoiceNo,'');assert.equal(cleared.invoiceDate,model.today());assert.equal(cleared.rows.length,5);assert(cleared.rows.every(r=>r.date===''&&r.meetha===0&&r.flavour===0));
assert.equal(model.totals(cleared.rows,cleared).grandTotal,0);assert.equal(cleared.meethaRate,custom.meethaRate);assert.equal(cleared.flavourRate,custom.flavourRate);assert.equal(cleared.address,custom.address);
assert.equal(resetApp.state(),'saved');assert(closed);assert.equal(resetApp.activeDate(),0);assert.equal(resetApp.fillOpen(),false);assert.equal(resetApp.clipboardText(),'');assert.equal(resetApp.resetting(),false);
assert.deepEqual((await api('/api/invoices/'+legacyId)).invoice,old);assert.equal((await api('/api/invoices')).invoices.length,2);
resetApp.ngOnDestroy();console.log('PASS: reset confirmation leaves data intact, confirmed reset persists after an in-flight save, zero totals, retained rates/address and preserved other invoices.');
console.log('Browser UI / supported WebMCP context unavailable; no browser QA claimed.');
